# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                        ___ _ _   _      _       ___ ___                      ┃
# ┃                       / __(_) |_| |__ _| |__   / __|_ _|                     ┃
# ┃                      | (_ | |  _| / _` | '_ \ | (__ | |                      ┃
# ┃                       \___|_|\__|_\__,_|_.__/  \___|___|                     ┃
# ┃                                                                              ┃
# ┃        This is where all our juicy tests and build jobs get defined.         ┃
# ┃              Before committing, please find the CI-linter here:              ┃
# ┃         https://gitlab.silverfin.com/devops/docker/sf-base/-/ci/lint         ┃
# ┃                                                                              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

###################
# Global settings #
###################
stages:
  - build
  - test
  - release
  - deploy

before_script:
  - 'echo "* COMMIT: $CI_COMMIT_SHA"'
  - 'echo "* TAG: $CI_COMMIT_TAG"'
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

#####################
# Reference objects #
#####################

########
# Jobs #
########

# Stage: build
build:
  tags:
    - docker-build
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" --build-arg "source_commit=$CI_COMMIT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    - retry "docker login -u 'gitlab-ci-token' -p $CI_BUILD_TOKEN $CI_REGISTRY; docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - retry "docker login -u 'gitlab-ci-token' -p $CI_BUILD_TOKEN $CI_REGISTRY; docker push $CI_REGISTRY_IMAGE:latest"
  only:
    - gitlab

deploy:
  stage: deploy
  tags:
    - docker-2
  image: "registry.silverfin.com/devops/docker/gitlab-toolbelt:2.5.0"
  only:
    - gitlab
  script:
    - find kubernetes -iname "*.yml" -exec sed -i "s/__COMMIT__/${CI_COMMIT_SHA}/g" {} \;
    - find kubernetes -iname "*.yml" -exec sed -i "s/__GITLAB_TOKEN__/${GITLAB_TOKEN}/g" {} \;
    - find kubernetes -iname "*.yml" -exec sed -i "s#__GITLAB_ENDPOINT__#${GITLAB_ENDPOINT}#g" {} \;
    - find kubernetes -iname "*.yml" -exec sed -i "s#__dockercfg__#${dockercfg}#g" {} \;
    - find kubernetes -iname "*.yml" -exec sed -i "s/__STRATEGY__/${STRATEGY}/g" {} \;
    - find kubernetes -iname "*.yml" -exec sed -i "s/__PR_LABEL__/${PR_LABEL}/g" {} \;
    - find kubernetes -iname "*.yml" -exec sed -i "s/__WC_GETSILVERFIN_COM_KEY__/${WC_GETSILVERFIN_COM_KEY}/g" {} \;
    - gcloud.account.configure.miscellaneous-001 ${GITLAB_SERVICE_ACCOUNT}
    - gcloud container clusters get-credentials miscellaneous-001 --region europe-west1
    - kubectl apply -R -f kubernetes/
    - kubectl rollout status deployment pr-bot -n pr-bot
    - echo "PR-Bot deployment rolled out to miscellaneous-001" | p2s '#dev-deploys'
